### ISSUE TITLE
Request: Level Select

### ISSUE THREAD

**Issue by veliusiidx** [nightmareci/the-absolute-reference#4]
Debug mode is okay for being able to quickly select Death 500 or practice the end roll in Master, but isn't good for any other speed setting.

It'd be great if the Debug Mode code could be modified to let people select levels they would like to practice IE. Death 300.

**Comment by nightmareci** [comment]
My goal with this project is to remain as much as possible identical to the original, without changing gameplay behavior. This constitutes a change to the game logic, which I won't do; I leave that up to fork authors. The debug mode isn't my addition, it's identical to the original's debug mode. This repository isn't a "fan game", open to any new fancy feature for fans, it's supposed to be a "better than an emulator" option to play the original game.

In the future, I might even make a fork with changes like your request here. But not in this repository.
